spring: 
  profiles:
    active:
    - dev
--- 
server:
  port: 8001
spring: 
   profiles: dev
   application:
    name: cloud-payment    #指定注册到注册中心的实例名称
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver             # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8     # 数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
      
#mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:mapping/*.xml
 
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: cloud-payment8001   #自定义服务名称信息
    prefer-ip-address: true     #访问路径可以显示IP地址
 
info:
  app.name: hc-cloud2020
  company.name: www.haochenit.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
server:
  port: 8001
spring: 
   profiles: test
   application:
    name: cloud-payment    #指定注册到注册中心的实例名称
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver             # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8     # 数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
  
  
#mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:mapping/*.xml
 
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: cloud-payment8001   #自定义服务名称信息
    prefer-ip-address: true     #访问路径可以显示IP地址
 
info:
  app.name: hc-cloud2020
  company.name: www.haochenit.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
